import type { Metadata } from "next";
import { recoleta, inter, poppins } from "@/lib/fonts";
import "./globals.css";
import TopNavbar from "./(shared)/top-navbar";
import FooterGutter from "./(shared)/footer-gutter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${recoleta.variable} ${inter.variable} ${poppins.variable} scroll-smooth antialiased font-inter bg-[#FDF6EE]`}
      >
        <div className="min-h-screen bg-brand-primary flex flex-col">
          <TopNavbar />
          <main className="w-full flex-1">{children}</main>
          <FooterGutter />
        </div>
      </body>
    </html>
  );
}
